## Alacritty toml V2
# @StefanModer

#### Themes
import = [
  "~/.config/alacritty/themes/sonokai.toml"
]

#### Window
[window]
option_as_alt = "OnlyLeft"
decorations = "None"
opacity = 0.87

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
italic = { family = "Maple Mono NF", style = "Italic"}

[mouse]
hide_when_typing = true

