[colors.primary]
background = "#2c2e34"
foreground = "#e2e2e3"
dim_foreground = "#838ba7"
bright_foreground = "#e2e2e3"

[colors.cursor]
text = "#2c2e34"
cursor = "#f2d5cf"

[colors.vi_mode_cursor]
text = "#2c2e34"
cursor = "#babbf1"

[colors.search.matches]
foreground = "#2c2e34"
background = "#a5adce"

[colors.search.focused_match]
foreground = "#2c2e34"
background = "#a6d189"

[colors.footer_bar]
foreground = "#2c2e34"
background = "#a5adce"

[colors.hints.start]
foreground = "#2c2e34"
background = "#e5c890"

[colors.hints.end]
foreground = "#2c2e34"
background = "#a5adce"

[colors.selection]
text = "#2c2e34"
background = "#f2d5cf"

[colors.normal]
black = "#181819"
red = "#fc5d7c"
green = "#9ed072"
yellow = "#e7c664"
blue = "#76cce0"
magenta = "#b39df3"
cyan = "#f39660"
white = "#e2e2e3"

[colors.bright]
black = "#7f8490"
red = "#fc5d7c"
green = "#9ed072"
yellow = "#e7c664"
blue = "#76cce0"
magenta = "#b39df3"
cyan = "#f39660"
white = "#e2e2e3"

[colors.dim]
black = "#181819"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#b5bfe2"

[[colors.indexed_colors]]
index = 16
color = "#ef9f76"

[[colors.indexed_colors]]
index = 17
color = "#f2d5cf"
